#!/bin/bash
#
# An example hook script that is called after a successful
# commit is made.
#
# To enable this hook, rename this file to "post-commit".
source ~/colors.sh

#: Nothing

VERSION=`git rev-list HEAD | wc -l`
#echo -en "\n\nVersão atualizada: $red localmente! $normal $VERSION\n\n"
echo -en "\n\nVersão atualizada: $magenta $VERSION $normal Somente localmente mande um \e[0;33m ® \e[31m na fé! $WHITE † \e[0;0m \n\n"
