#!/bin/bash



#Se nulo
if [ -z "$1" ]; then

echo -e "Use: $0 add/install <PACOTE>
     $0 list\n"

fi


if [ "$1" == "add" ] || [ "$1" == "install" ]; then
pkg_add $2

elif [ "$1" == "list" ]; then

curl -s $PKG_PATH | cut -d'"' -f6 | egrep -v '(<|>)'

fi
