- hosts: localhost
  become: yes
  become_user: root
  vars:
    #nodes is only for view in --report output(DEBUG)
    nodes:
      - webmail
      - linux
      - hp
      - storage
      - mail
      - servidorpush
      - servidorpush.superati.com.br
      - dev1
      - dev10

    resolv_nameservers:
      - 192.168.15.10
      - 192.168.15.1
      - 192.168.15.15
      - 8.8.8.8
      - 4.4.4.4

    resolv_domain: pactual.net
    resolv_search:
      - vertzon.intranet
      - home

    resolv_options:
      - timeout:2
      - rotate

  tasks:
#      - debug:
#          msg: "{{ vars['nodes'] }}"

      - name: update /etc/hosts file
        blockinfile:
            dest: /etc/hosts
            content: "{{ lookup('template', 'all_hosts.j2') }}"
            state: present

      - name: update /etc/resolv.conf file
        blockinfile:
            dest: /etc/resolv.conf
            content: "{{ lookup('template', 'resolv_conf.j2') }}"
            state: present
