- hosts: localhost
  become: yes
  become_user: root
  vars:
       nodes:
        - webmail
        - linux
        - hp
        - node3
  tasks:
      - debug:
          msg: "{{ vars['nodes'] }}"

      - name: update /etc/hosts file
        blockinfile:
            dest: /etc/hosts
            content: "{{ lookup('template', 'all_hosts.j2') }}"
            state: present
