#!/bin/bash


SCREEN_BIN=$( type screen | cut -f3 -d' ')

if [ -e $SCREEN_BIN ]; then
    screen -c $CDSHELL/install/install.screen
else
    echo -en "alert Não localizado binário do screen no PATH$normal\n"
    echo usando instalacao padrao ./install.sh
    cdshell -i
    nohup bash $CDSHELL/linux/notificar.sh 2>&1 /dev/null
fi


