#!/bin/bash


SCREEN_BIN=$( type screen | cut -f3 -d' ')

if [ -e $SCREEN_BIN ]; then
    unalias screen
    screen -c $CDSHELL/install/install.screen
else
    echo  nao existe screen
    echo usando instalacao padrao ./install.sh
    cdshell -i
fi


