#!/bin/bash

#################################################
# Bash script - start.sh				#
# Facilitador acesso a systemctl start e ja     #
# exibe status de execucao do servico.		#
# v_1.0.1							#
#################################################


#############     CONFIG     ####################
#Carrega variáreis de ambiente.
source ~/.export
# Suporte a cores no bash.
source ~/shell/colors.sh
################################################

OPTIONS="-a -e -h"
##########  Funcao       #######################
function help(){
	echo -en "\n\t $alert Use $0 $OPTIONS $normal\n\n"
	return 0
}



################################################
#############        MAIN       ################
case $1 in

		"-h" | "--help" )	
			# Faça isso... 
			echo -en "Help $0 \n\n Digite os exemplos aqui:"
		;;

	
		# Cdshell - Ansible Add Host
		* )

			if [ ! -z $1 ]; then
				HOST = $1
				echo $HOST
			else
				help
			fi

		;;
esac
#############        FIM      ##################
################################################

