#!/bin/bash



if [ ! -d ~/.lixeira ] ; then
mkdir ~/.lixeira
echo Diretório nao existia, foi criado com sucesso.
echo Manda de novo o comando agora.

else
# SOLUCAO ELEGANTE, nao precisa parsear a porra do array da linha de comando procurando os parametros.
mv $@ ~/.lixeira/
fi

