#!/usr/bin/expect

set timeout 5

set arg1 [lindex $argv 0]
set arg2 [lindex $argv 1]

puts $arg2

set fd1 [open "~/padrao1.passwd"]
set senha [read $fd1]


spawn sftp -o "StrictHostKeyChecking no" tqi_rcastro@$arg1
expect "*assword:"
send "$senha\r"

expect "sftp>"
interact
