#!/usr/bin/expect

# Se setar o timeout a probabilidade de digitar a senha qdo algum servidor atrasar é grande.

#set timeout 5

set arg1 [lindex $argv 0]
set arg2 [lindex $argv 1]

puts $arg2

set fd1 [open "~/padrao1.passwd"]
set senha [read $fd1]


spawn ssh -o "StrictHostKeyChecking no" -l tqi_rcastro $arg1
expect "*assword:"
send "$senha\r"

expect "*$*"
if [string match "" $arg2] {
	send "sudo su -"
} else {
	send $arg2
}
send "\r"
interact
